[phases.setup]
nixPkgs = ["python310Full", "cairo", "pango"]

[phases.install]
cmds = ["python3 -m ensurepip --upgrade || python3 -m pip install --upgrade pip || true", "python3 -m pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "python3 -m uvicorn server:app --host 0.0.0.0 --port $PORT"
