[phases.setup]
nixPkgs = ["python310", "cairo", "pango"]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = ". /opt/venv/bin/activate && uvicorn server:app --host 0.0.0.0 --port $PORT"
